using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using CopilotSessionManager.Core.Models;

namespace CopilotSessionManager.Core.Sessions;

/// <summary>
/// Default <see cref="ISessionReadmeRenderer"/>. Produces deterministic,
/// metadata-driven markdown. Section order:
/// <list type="number">
///   <item>Overview (auto)</item>
///   <item>Activity (auto)</item>
///   <item>Goal (auto)</item>
///   <item>History (auto)</item>
///   <item>Notes (user-editable)</item>
///   <item>Next steps (user-editable)</item>
/// </list>
/// </summary>
public sealed class TemplatedSessionReadmeRenderer : ISessionReadmeRenderer
{
    /// <summary>Marker that introduces a user-editable block.</summary>
    public const string UserBeginPrefix = "<!-- USER:BEGIN ";

    /// <summary>Marker that closes a user-editable block.</summary>
    public const string UserEndPrefix = "<!-- USER:END ";

    /// <summary>Common closing token for the markers.</summary>
    public const string MarkerSuffix = " -->";

    /// <summary>Names of every user-editable block this renderer emits, in order.</summary>
    public static readonly string[] UserBlockNames = { "notes", "next-steps" };

    private readonly TimeProvider _timeProvider;

    public TemplatedSessionReadmeRenderer(TimeProvider? timeProvider = null)
    {
        _timeProvider = timeProvider ?? TimeProvider.System;
    }

    public string Render(SessionReadmeContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        var s = context.Session;
        var sb = new StringBuilder(2048);
        var ts = _timeProvider.GetUtcNow();

        sb.Append("# ").AppendLine(EscapeInline(BuildTitle(s)));
        sb.AppendLine();
        sb.Append("_Auto-generated by Copilot Session Manager on ")
          .Append(ts.ToString("u", CultureInfo.InvariantCulture))
          .AppendLine(". User-editable blocks are preserved across regeneration._");
        sb.AppendLine();

        AppendOverview(sb, s, context.Label);
        AppendActivity(sb, s);
        AppendGoal(sb, s);
        AppendHistory(sb, context);
        AppendUserBlock(sb, "notes", "Notes",
            "Add anything worth remembering about this session — decisions, gotchas, references.");
        AppendUserBlock(sb, "next-steps", "Next steps",
            "What's the next thing to do when picking this back up?");

        return sb.ToString();
    }

    private static string BuildTitle(Session s) =>
        !string.IsNullOrWhiteSpace(s.Summary)
            ? Truncate(s.Summary!, 120)
            : $"Session {ShortId(s.Id)}";

    private static void AppendOverview(StringBuilder sb, Session s, SessionType label)
    {
        sb.AppendLine("## Overview");
        sb.AppendLine();
        sb.Append("- **Session id:** `").Append(s.Id).AppendLine("`");
        sb.Append("- **Label:** ").AppendLine(label.ToString());
        sb.Append("- **Status:** ").AppendLine(s.Status.ToString());
        sb.Append("- **Repository:** ").AppendLine(EscapeInline(s.Repository ?? "_(none)_"));
        sb.Append("- **Branch:** ").AppendLine(EscapeInline(s.Branch ?? "_(none)_"));
        sb.Append("- **Working directory:** ").AppendLine(FormatPath(s.Cwd));
        if (!string.IsNullOrWhiteSpace(s.HostType))
        {
            sb.Append("- **Host:** ").AppendLine(EscapeInline(s.HostType!));
        }
        sb.AppendLine();
    }

    private static void AppendActivity(StringBuilder sb, Session s)
    {
        sb.AppendLine("## Activity");
        sb.AppendLine();
        sb.Append("- **Created:** ").AppendLine(FormatTimestamp(s.CreatedAt));
        sb.Append("- **Last updated:** ").AppendLine(FormatTimestamp(s.UpdatedAt));
        sb.Append("- **Turns:** ").AppendLine(s.TurnCount.ToString(CultureInfo.InvariantCulture));
        if (s.Locks.Count > 0)
        {
            var owners = string.Join(", ", s.Locks.Select(l => $"PID {l.ProcessId}"));
            sb.Append("- **Active locks:** ").AppendLine(owners);
        }
        sb.AppendLine();
    }

    private static void AppendGoal(StringBuilder sb, Session s)
    {
        sb.AppendLine("## Goal");
        sb.AppendLine();
        if (string.IsNullOrWhiteSpace(s.Summary))
        {
            sb.AppendLine("_(No summary recorded by the CLI yet.)_");
        }
        else
        {
            sb.AppendLine(s.Summary!.Trim());
        }
        sb.AppendLine();
    }

    private static void AppendHistory(StringBuilder sb, SessionReadmeContext ctx)
    {
        sb.AppendLine("## History");
        sb.AppendLine();
        if (ctx.Checkpoints.Count == 0)
        {
            sb.AppendLine("_(No checkpoints recorded.)_");
        }
        else
        {
            foreach (var cp in ctx.Checkpoints)
            {
                sb.Append("- **")
                  .Append(cp.Number.ToString("D3", CultureInfo.InvariantCulture))
                  .Append("** — ")
                  .AppendLine(EscapeInline(cp.Title));
            }
        }
        sb.AppendLine();
    }

    private static void AppendUserBlock(StringBuilder sb, string name, string heading, string placeholder)
    {
        sb.Append("## ").AppendLine(heading);
        sb.AppendLine();
        sb.Append(UserBeginPrefix).Append(name).AppendLine(MarkerSuffix);
        sb.Append("_").Append(placeholder).AppendLine("_");
        sb.Append(UserEndPrefix).Append(name).AppendLine(MarkerSuffix);
        sb.AppendLine();
    }

    private static string FormatTimestamp(DateTimeOffset ts) =>
        ts == DateTimeOffset.MinValue
            ? "_(unknown)_"
            : ts.ToString("u", CultureInfo.InvariantCulture);

    private static string FormatPath(string? path) =>
        string.IsNullOrWhiteSpace(path) ? "_(none)_" : "`" + path + "`";

    private static string ShortId(string id) =>
        id.Length <= 8 ? id : id[..8];

    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..max] + "…";

    private static string EscapeInline(string value)
    {
        // Defensive: prevent stray markdown control chars in metadata from
        // breaking the layout. We only need to keep formatting predictable;
        // this is not a security boundary.
        return value
            .Replace("\r", string.Empty, StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);
    }
}
